[TASK] Add TYPO3 template / add empty column option

diff --git a/build/docker/entrypoint b/build/docker/entrypoint
--- a/build/docker/entrypoint
+++ b/build/docker/entrypoint
@@ -24,18 +24,28 @@ if [ "$HOSTUSER_UID" -gt "0" ]; then
     # unix
     # if a user within the container has already the id HOSTUSER_UID
     if [ "$HOSTUSER_UID" -ne "$OLD_USER_UID" ] && [ ! -z "$MAYBEUSER_UID" ]; then
-        echo "There is already a user with the uid $HOSTUSER_UID in the container!".
-        echo "You need to change your host user id. Sorry!".
-        echo "Tip: Your host user id should be greater than 410 to avoid this error.".
+        echo "There is already a user with the uid $HOSTUSER_UID in the container!"
+        echo "You need to change your host user id. Sorry!"
+        echo "Tip: Your host user id should be greater than 410 to avoid this error."
         exit 1;
     fi
 
     # if a user group within the container has already the id HOSTUSER_GID
     if [ "$HOSTUSER_GID" -ne "$OLD_USER_GID" ] && [ ! -z "$MAYBEUSER_GID" ]; then
-        echo "There is already a user group with the uid $HOSTUSER_GID in the container!".
-        echo "You need to change your host user group id. Sorry!".
-        echo "Tip: Your host user group id should be greater than 410 to avoid this error.".
+        echo "There is already a user group with the uid $HOSTUSER_GID in the container!"
+        echo "You need to change your host user group id. Sorry!"
+        echo "Tip: Your host user group id should be greater than 410 to avoid this error."
         exit 1;
+    fi
+
+    if [ "$1" == "--alternative-data-dir" ]; then
+        if [ ! -d "$2" ]; then
+            echo "The data dir '$2' does not exist."
+            exit 1;
+        fi
+
+        rsync -raq "${2%/}/" /opt/pseudify/userdata/
+        shift 2
     fi
 
     ARGUMENTS="$@"
@@ -44,6 +54,7 @@ if [ "$HOSTUSER_UID" -gt "0" ]; then
         && groupmod -g $HOSTUSER_GID pseudify > /dev/null \
         && usermod -g $HOSTUSER_GID pseudify > /dev/null \
         && if [ -z \"\$( ls -A /opt/pseudify/userdata/ )\" ]; then sudo -E -H -u pseudify rsync -raq /opt/pseudify/userdata_template/ /opt/pseudify/userdata/; else rm -rf /opt/pseudify/userdata/var/; fi \
+        && chown $HOSTUSER_UID:$HOSTUSER_GID -R /opt/pseudify/userdata/ > /dev/null \
         && cd /opt/pseudify/core/ \
         && sudo -E -H -u pseudify composer install --no-dev --optimize-autoloader --classmap-authoritative --no-progress --no-interaction --quiet > /dev/null \
         && exec sudo -E -H -u pseudify php /opt/pseudify/core/bin/pseudify $ARGUMENTS; \
